#%RAML 0.8
title: Dummy API
version: 1
baseUri: https://api.intraway.com
documentation:
  - title: Custom 1
    content: |
      _Lorem ipsum_ dolor sit amet, consectetur adipiscing elit. Mauris non neque dolor. In laoreet mauris non orci auctor, non gravida urna fringilla. Vestibulum ac nibh et risus suscipit aliquam eget ullamcorper magna. Morbi placerat consectetur nunc, a commodo lorem commodo sit amet. Sed bibendum ullamcorper orci nec efficitur. Integer non lacinia neque. Aliquam placerat, turpis a vulputate maximus, erat sem ullamcorper nisl, vel tempor lorem lacus ac orci. Suspendisse potenti. Fusce sit amet massa quam. Sed ac placerat massa, vel finibus lacus. Nam nec dolor ac enim varius cursus.

  - title: Custom 2
    content: !include custom2.md
